image: gitpod/workspace-postgres

tasks:
  - init: npm install && npm run build
    command: 
     npm run dev

ports:
  - port: 5173
    onOpen: open-browser   
  - port : 5432
    onOpen: ignore 



vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true